---
  apiVersion: v1
  kind: Namespace
  metadata:
    name: datawire

---
  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: sentinel
    namespace: datawire
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: sentinel
      spec:
        volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: docker-directory
          hostPath:
            path: /var/lib/docker
        - name: config-volume
          configMap:
            name: sentinel-config
        containers:
        - name: sentinel
          image: us.gcr.io/datawireio/sentinel:0.1.18
          securityContext:
            privileged: true
          env:
          - name: ENV
            value: develop
          - name: MDK_SERVICE_NAME
            value: sentinel
          - name: MDK_SERVICE_VERSION
            value: "0.1.18"
          - name: DATAWIRE_TOKEN
            valueFrom:
              secretKeyRef:
                name: datawire
                key: token
          - name: DATAWIRE_GOOG_TOKEN
            valueFrom:
              secretKeyRef:
                name: datawire-goog
                key: google
          - name: DATAWIRE_ROUTABLE_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: DATAWIRE_ROUTABLE_PORT
            value: "5000"
          volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-sock
            readOnly: false
          - mountPath: /var/lib/docker
            name: docker-directory
            readOnly: false
          - name: config-volume
            mountPath: /opt/sentinel/config
          ports:
          - containerPort: 5000

---
  kind: Service
  apiVersion: v1
  metadata:
    name: sentinel
    namespace: datawire
  spec:
    selector:
      app: sentinel
    ports:
      - protocol: TCP
        port: 5000
        targetPort: 5000
        name: sentinel
